object VersionConstants {
    const val userdevVersion = "1.3.8"
    const val pluginYmlVersion = "0.5.2"
    const val shadowVersion = "7.1.2"
    const val minecraftVersion = "1.19.1-R0.1-SNAPSHOT"
    const val cloudVersion = "1.7.0"
    const val adventureVersion = "4.12.0-SNAPSHOT"
    const val adventurePlatformVersion = "4.1.1"
    const val paperLibVersion = "1.0.7"
    const val bStatsVersion = "3.0.0"
    const val minecraftReflectionVersion = "123e2f546c"
    const val placeholderapiVersion = "2.11.2"
    const val commodoreVersion = "2.0"
    const val brigadierVersion = "1.0.18"
    const val assertjVersion = "3.23.1"
    const val mockitoVersion = "4.6.1"
    const val jupiterVersion = "5.8.2"
}
