object VersionConstants {
    const val userdevVersion = "1.5.3"
    const val pluginYmlVersion = "0.5.2"
    const val shadowVersion = "7.1.2"
    const val minecraftVersion = "1.19.3-R0.1-SNAPSHOT"
    const val cloudVersion = "1.8.0"
    const val adventureVersion = "4.12.0"
    const val adventurePlatformVersion = "4.2.0"
    const val paperLibVersion = "1.0.8-SNAPSHOT"
    const val bStatsVersion = "3.0.0"
    const val minecraftReflectionVersion = "123e2f546c"
    const val placeholderapiVersion = "2.11.2"
    const val commodoreVersion = "2.2"
    const val brigadierVersion = "1.0.18"
    const val assertjVersion = "3.23.1"
    const val mockitoVersion = "4.11.0"
    const val jupiterVersion = "5.9.1"
}
