name: "Publish Insights"

on:
  release:
    branches: [main]
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish to Modrinth
        run: "./gradlew modrinth"
        env:
          CHANGE_LOG: ${{ github.event.release.body }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Publish to Repository
        run: "./gradlew publish"
        env:
          JSINCO_REPO_USERNAME: ${{ secrets.JSINCO_REPO_USERNAME }}
          JSINCO_REPO_SECRET: ${{ secrets.JSINCO_REPO_SECRET }}